title: Norwegian Life Science Data Management LookUp
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: ''
# this appears on the top navigation bar next to the home button

description: "RDM guidance for life scientists in Norway"
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme@1.23.0

dsw_deep_link_prefix: https://elixir-no.ds-wizard.org/projects/create/from-template?selected=

theme_variables:
  theme_color: da366e
  fonts:
    - https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap
  github_buttons:
    position: top
    edit_me: true
    open_issue: true
    history: true
  topnav:
    theme: light
    brand_logo: assets/img/main_logo.svg
    github: true

permalink: pretty

exclude:
  - README.md
  - /vendor

defaults:
-
  scope:
    path: ""
    type: "pages"
  values:
    permalink: /:basename
    layout: "page"
    sidebar: main
    topnav: topnav
-
  scope:
    path: "pages/cheat_sheets"
    type: "cheat_sheet"
  values:
    permalink: /:basename
    layout: "page"
    sidebar: cheat_sheets
    topnav: topnav
-
  scope:
    path: "pages/about"
    type: "pages"
  values:
    permalink: /:basename
    layout: "page"
    topnav: topnav
    sidebar: about


plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
